---
include:
  - board: nice_nano//zmk
    shield: sofle_left
    artifact-name: sofle_left_supermini
    cmake-args: >-
     -DCONFIG_ZMK_WPM=y
     -DCONFIG_ZMK_WIDGET_WPM_STATUS=y
     -DCONFIG_ZMK_WIDGET_LAYER_STATUS=y
     -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
     -DCONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
     -DCONFIG_LV_Z_MEM_POOL_SIZE=4096
     -DCONFIG_LV_USE_THEME_MONO=y
     -DCONFIG_LV_USE_LABEL=y
     -DCONFIG_LV_FONT_MONTSERRAT_10=y
     -DCONFIG_LV_FONT_MONTSERRAT_12=y
     -DCONFIG_LV_FONT_MONTSERRAT_14=y
     -DZMK_EXTRA_MODULES=/__w/zmk-config/zmk-config/modules/sofle_oled

  - board: nice_nano//zmk
    shield: sofle_right
    artifact-name: sofle_right_supermini

  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: settings_reset_supermini