# OLED
CONFIG_ZMK_DISPLAY=y
CONFIG_SSD1306=y

# Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# RGB
CONFIG_ZMK_RGB_UNDERGLOW=y

# No mostrar USB/Bluetooth
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=n